[core]
    engine = pg
    top_dir = .
    plan_file = sqitch.plan
    deploy_dir = deploy
    revert_dir = revert
    verify_dir = verify

[target "local"]
    uri = db:pg://papertrail:local-only-change-me@postgres:5432/papertrail
