package com.papertrail.api.scholarly.acquisition.domain

enum class CitedPaperAccessCause {
    NO_ACCESSIBLE_METADATA,
    NO_FULL_TEXT_LOCATION_RETURNED,
    FULL_TEXT_LOCATION_LICENSE_MISSING,
    FULL_TEXT_LOCATION_LICENSE_REJECTED,
    FULL_TEXT_LOCATION_URL_REJECTED,
    FULL_TEXT_DOWNLOAD_FAILED,
    FULL_TEXT_FORMAT_UNSUPPORTED,
    FULL_TEXT_PARSE_FAILED,
    LANGUAGE_UNSUPPORTED,
}
