package com.papertrail.api.providers

fun reviewedExternalProviderCatalog(): ProviderCatalog = ProviderCatalog(
    listOf(
        ProviderRegistration(
            CLAIM_EXTRACTOR_ROLE,
            "heuristic",
            "Heuristic",
            "v1",
            null,
            ProviderTrustBoundary.LOCAL,
            true,
            setOf(DataCategory.CITATION_CONTEXT),
        ),
        ProviderRegistration(
            CLAIM_EXTRACTOR_ROLE,
            "reviewed-llm",
            "Reviewed LLM",
            "v1",
            "model-1",
            ProviderTrustBoundary.EXTERNAL,
            true,
            setOf(DataCategory.CITATION_CONTEXT),
            retentionDisclosure = "Reviewed retention and deletion terms for this test deployment.",
            enablementReviewed = true,
        ),
        ProviderRegistration(
            EMBEDDING_ROLE,
            "local",
            "Local embeddings",
            "v1",
            "e5-small-v2",
            ProviderTrustBoundary.LOCAL,
            true,
            setOf(DataCategory.CITED_PAPER_CHUNKS, DataCategory.EMBEDDING_INPUT),
        ),
        ProviderRegistration(
            SYSTEM_ONE_ROLE,
            "mock",
            "Mock",
            "v1",
            "mock-v1",
            ProviderTrustBoundary.LOCAL,
            true,
            setOf(DataCategory.ATOMIC_CLAIMS, DataCategory.EVIDENCE_PASSAGES),
        ),
        ProviderRegistration(
            SYSTEM_ONE_ROLE,
            "unreviewed-provider",
            "Unreviewed provider fixture",
            "unknown",
            null,
            ProviderTrustBoundary.UNREVIEWED,
            false,
            setOf(DataCategory.ATOMIC_CLAIMS, DataCategory.EVIDENCE_PASSAGES),
        ),
    ),
)
